title: Triston Thompson - OSINT Learning Journey
description: Documenting my journey learning Open Source Intelligence from scratch
author: Triston Thompson
email: tbt5417@psu.edu
github_username: Tempest255 


theme: minima


show_excerpts: true
